version: '3'
services:
  mongodb:
    build:
      context: mongo
    image: ${REPO}/test
    networks:
      - robot-shop
    logging: &logging
      driver: "json-file"
      options:
        max-size: "25m"
        max-file: "2"
 

networks:
  robot-shop:

